### ISSUE TITLE
El Capitan: update/install fails

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/osx-setup#104]
Known issues:
- [ ] gcc doesn't install/compile
- [ ] python doesn't install/compile
- [ ] mysql-connector doesn't install/compile
- [ ] ...

Basically fails the software which require gcc build.

TODO:
- [ ] Possibly upgrade XCode tools to 6.3 will solve the problem (`xcode-select --install` does the update)

**Comment by njam** [comment]
@cargomedia/dev please wait with upgrading to the new OSX "El Capitan" until we have resolved open issues.

**Comment by kris-lab** [comment]
WORKING STEPS:
1. Make sure you have OS, XCode updates (using AppStore/updates)
2. `sudo chown $(whoami):admin /usr/local && sudo chown -R $(whoami):admin /usr/local`
3. `xcode-select --install` will update current tools
4. `sudo xcodebuild -license` will accept license for xcode tools
5. typical [osx-setup](https://github.com/cargomedia/osx-setup#run-the-installer) will update your system

Some problems:
- if you have installed `php@5.6` or `php@5.4` then it can conflict with `php@5.5`. I would suggest `brew unlink php56` and `brew unlink php54` then!

PLEASE WAIT WITH UPGRADE AS LONG AS THIS TICKET IS OPEN.

**Comment by alexispeter** [comment]
I'm still on mavericks :D

**Comment by vogdb** [comment]
I should have done the same. This damned Yosemite...

**Comment by njam** [comment]
@tomaszdurka you did a fresh install of El Capitan.

Does everything work?
Can you confirm that any puppet-packages spec run successfully?

**Comment by njam** [comment]
@tomaszdurka ?

**Comment by tomaszdurka** [comment]
Yes, I did reinstall vagrant 1.7.4 with all the plugins. Run vim spec - worked.

**Comment by njam** [comment]
@cargomedia/dev Tomasz did a fresh install of El Capitan and everything seems to work so far. Some devs have also upgraded to El Capitan. So feel free to upgrade. Just make sure to keep Vagrant at 1.7.x!
