### ISSUE TITLE
Add global BUNDLE_PATH

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/osx-setup#105]
Idea is to install bundle deps locally in project folder. To achieve that we need to set default, relative `BUNDLE_PATH=./vendor/bundle`.

**Comment by njam** [comment]
@tomaszdurka I suggest to rather do this per repo, as it will affect the files in the repo (need to gitignore that path).
Like here: https://github.com/cargomedia/puppet-packages/pull/1146

wdyt?

**Comment by tomaszdurka** [comment]
Well, that would be the same as we treat `vendor` directory in php projects.

I am ok to do it per project too.

**Comment by njam** [comment]
But for bundler this is not default, so usually other developer will not have it.

**Comment by njam** [comment]
You can create a file `~/.bundle/config` with the following contents to accomplish this:
```
BUNDLE_PATH: "./vendor/bundle"
```
